### ISSUE TITLE
Short Bio

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/omp-1.1.1.0#1]
The Biography on an author appears only in the moment of writing it. As soon as the site is "saved" instead of the biography "<" appears.
![omp_1_1_1_kurzbio_autor](https://cloud.githubusercontent.com/assets/11088169/13256916/e5c061da-da4c-11e5-851c-5a3c3f9f5817.png)

**Comment by kadowa** [comment]
Was ist denn omptest für eine Instanz? Ist das Verhalten in der Produktivinstanz identisch? In der Datenbank sind einige Biografieeinträge für Autoren vorhanden, es handelt sich also möglicherweise nur um ein Anzeigeproblem.

**Comment by AnjaKonopka** [comment]
Das Verhalten in der OMP-Produktivinstanz ist identisch. Mittlerweile glaube ich auch, dass es nur ein Darstellungsproblem ist. Ich hatte die Bio-Daten für den Band von Marie Sander in der Produktivinstanz erneuert, ohne dass dies Auswirkungne auf der heiUP-Website zeigte. Jetzt habe ich aber bei Anna Völlner gerade gesehen, dass die Verknüpfung zwischen OMP und dem Sander-Band noch gar nicht aktiviert ist.

**Comment by ankosi** [comment]
Der Bug ist mir Release 1.2. behoben.
