### ISSUE TITLE
neue repo ?

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/omp-1.1.1.0#2]
@kadowa 
wozu braucht man  dieses repo? wäre ein branch in UB-Heidelberg/omp nicht sinnvoller?

**Comment by kadowa** [comment]
Anja hatte Probleme mit der alten OMP, die sie in GitHub dokumentieren wollte. Wir fanden, dass diese besser nicht in die OMP-1.2-Issues gehören, da wir in diesen ja Probleme mit der Entwicklerversion an PKP melden. Daher eine neues Repo (=separate Issues) statt Branch. Wenn die Testphase für OMP 1.2 vorbei ist, können wir es wieder löschen.

**Comment by withanage** [comment]
ok, kurzfrsitig  macht das Sinn, nur für unsere Benutzer freizugeben.
