### ISSUE TITLE
arthistoricum.net Serien alphabetisch anordnen

### ISSUE THREAD

**Issue by bettinamueller** [UB-Heidelberg/omp-1.1.1.0#4]
Lieber Dulip, liebe Katharina,
können hier die Serien bitte alphabetisch anordnet werden? 
http://books.ub.uni-heidelberg.de/arthistoricum/series

LIebe Grüße und vielen Dank,
Eure Bettina

@kadowa @withanage

**Comment by kadowa** [comment]
Schon auf der Agenda: https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/28 :wink:
